# Generated by Django 4.2.7 on 2023-11-29 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_plan'),
        ('lead', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_comments', to='team.team'),
        ),
    ]
